export HOSTNAME="$HOST"
export HISTFILE="${ZDATADIR}/zsh_history"
export HISTSIZE=10000
export SAVEHIST=100000
export LISTMAX=1000

autoload -Uz compinit && compinit -u

# fnm setup
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi
